### ISSUE TITLE
Failure of building RaiSim with GLIBC version error

### ISSUE THREAD

**Issue by YiLin32Wang** [christsa/dgrasp#10]
Hi,

Thanks for the interesting work!

I'm trying to build install the physics simulation engine following the [INSTALLATION.md](https://github.com/christsa/dgrasp/blob/main/docs/INSTALLATION.md).

However, I'm stuck with the error when running `make install -j4`, where it appears as followed:

> [  1%] Linking CXX executable laikago
> [  2%] Linking CXX executable speed_test
> [  3%] Linking CXX executable primitives
> [  4%] Linking CXX executable meshes
> /home/datassd/yilin/raisim/raisim_build/dgrasp/raisim/linux/lib/libraisim.so.1.1.6: undefined reference to `log@GLIBC_2.29'
> /home/datassd/yilin/raisim/raisim_build/dgrasp/raisim/linux/lib/libraisim.so.1.1.6: undefined reference to `exp@GLIBC_2.29'
> collect2: error: ld returned 1 exit status
> examples/CMakeFiles/speed_test.dir/build.make:101: recipe for target 'examples/speed_test' failed
> make[2]: *** [examples/speed_test] Error 1
> CMakeFiles/Makefile2:203: recipe for target 'examples/CMakeFiles/speed_test.dir/all' failed
> make[1]: *** [examples/CMakeFiles/speed_test.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> /home/datassd/yilin/raisim/raisim_build/dgrasp/raisim/linux/lib/libraisim.so.1.1.6: undefined reference to `log@GLIBC_2.29'
> /home/datassd/yilin/raisim/raisim_build/dgrasp/raisim/linux/lib/libraisim.so.1.1.6: undefined reference to `exp@GLIBC_2.29'
> collect2: error: ld returned 1 exit status
> /home/datassd/yilin/raisim/raisim_build/dgrasp/raisim/linux/lib/libraisim.so.1.1.6: undefined reference to `log@GLIBC_2.29'
> /home/datassd/yilin/raisim/raisim_build/dgrasp/raisim/linux/lib/libraisim.so.1.1.6: undefined reference to `exp@GLIBC_2.29'
> examples/CMakeFiles/meshes.dir/build.make:101: recipe for target 'examples/meshes' failed
> make[2]: *** [examples/meshes] Error 1
> collect2: error: ld returned 1 exit status
> CMakeFiles/Makefile2:255: recipe for target 'examples/CMakeFiles/meshes.dir/all' failed
> make[1]: *** [examples/CMakeFiles/meshes.dir/all] Error 2
> /home/datassd/yilin/raisim/raisim_build/dgrasp/raisim/linux/lib/libraisim.so.1.1.6: undefined reference to `log@GLIBC_2.29'
> /home/datassd/yilin/raisim/raisim_build/dgrasp/raisim/linux/lib/libraisim.so.1.1.6: undefined reference to `exp@GLIBC_2.29'
> collect2: error: ld returned 1 exit status
> examples/CMakeFiles/laikago.dir/build.make:101: recipe for target 'examples/laikago' failed
> make[2]: *** [examples/laikago] Error 1
> CMakeFiles/Makefile2:281: recipe for target 'examples/CMakeFiles/laikago.dir/all' failed
> make[1]: *** [examples/CMakeFiles/laikago.dir/all] Error 2
> examples/CMakeFiles/primitives.dir/build.make:101: recipe for target 'examples/primitives' failed
> make[2]: *** [examples/primitives] Error 1
> CMakeFiles/Makefile2:229: recipe for target 'examples/CMakeFiles/primitives.dir/all' failed
> make[1]: *** [examples/CMakeFiles/primitives.dir/all] Error 2
> Makefile:135: recipe for target 'all' failed
> make: *** [all] Error 2
> 

which seems like some issues with the GLIBC version. However, the error remains even after I update my GLIBC to 2.29.

I'm wondering if you have ever seen this problem or have any ideas about this?

Thanks!

**Comment by YiLin32Wang** [comment]
Hi Sammy,

Thanks for the reply and help!

I've finally located and solved the problem and managed to install raisim. For people who may encounter the same problem on Ubuntu18.04, in my case it's not about gcc / libstdc++6 version in https://github.com/christsa/dgrasp/issues/9#issuecomment-1500862620,
but instead a problem about the lib soft linking to a older GLIBC version(2.27 in my case) on the machine. This requires updating the GLIBC to 2.29 and then soft link libm-2.29.so to libm.so.6. In my case, I didn't realize that soft linking libm-2.29.so to libm.so.6 was not successful with `ln -sf` after installing GLIBC2.29, where there wasn't any warning or error. After `sudo ln -sf`, it works well.

Thanks,
Yilin
